version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: flow_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fireplace_db
    ports:
      - "5556:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
