// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/plan/checklist.proto

package plan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChecklistService_CreateItem_FullMethodName        = "/plan.ChecklistService/CreateItem"
	ChecklistService_GetItem_FullMethodName           = "/plan.ChecklistService/GetItem"
	ChecklistService_ListItems_FullMethodName         = "/plan.ChecklistService/ListItems"
	ChecklistService_ListArchivedItems_FullMethodName = "/plan.ChecklistService/ListArchivedItems"
	ChecklistService_ListUpcomingItems_FullMethodName = "/plan.ChecklistService/ListUpcomingItems"
	ChecklistService_ListItemsByUser_FullMethodName   = "/plan.ChecklistService/ListItemsByUser"
	ChecklistService_UpdateItem_FullMethodName        = "/plan.ChecklistService/UpdateItem"
	ChecklistService_UpdateItemDates_FullMethodName   = "/plan.ChecklistService/UpdateItemDates"
	ChecklistService_ArchiveItem_FullMethodName       = "/plan.ChecklistService/ArchiveItem"
	ChecklistService_DeleteItem_FullMethodName        = "/plan.ChecklistService/DeleteItem"
	ChecklistService_DailyReset_FullMethodName        = "/plan.ChecklistService/DailyReset"
)

// ChecklistServiceClient is the client API for ChecklistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChecklistService — manages checklist items scoped to plans. Same package
// as PlanService because both belong to plan-service; one binary, two server
// registrations.
type ChecklistServiceClient interface {
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	ListArchivedItems(ctx context.Context, in *ListArchivedItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	ListUpcomingItems(ctx context.Context, in *ListUpcomingItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	ListItemsByUser(ctx context.Context, in *ListItemsByUserRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error)
	UpdateItemDates(ctx context.Context, in *UpdateItemDatesRequest, opts ...grpc.CallOption) (*ChecklistItem, error)
	ArchiveItem(ctx context.Context, in *ArchiveItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DailyReset un-completes all daily-scope items across all plans (job-scheduled,
	// called from the gateway's nightly job in 4c).
	DailyReset(ctx context.Context, in *DailyResetRequest, opts ...grpc.CallOption) (*DailyResetResponse, error)
}

type checklistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChecklistServiceClient(cc grpc.ClientConnInterface) ChecklistServiceClient {
	return &checklistServiceClient{cc}
}

func (c *checklistServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecklistItem)
	err := c.cc.Invoke(ctx, ChecklistService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecklistItem)
	err := c.cc.Invoke(ctx, ChecklistService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ChecklistService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) ListArchivedItems(ctx context.Context, in *ListArchivedItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ChecklistService_ListArchivedItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) ListUpcomingItems(ctx context.Context, in *ListUpcomingItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ChecklistService_ListUpcomingItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) ListItemsByUser(ctx context.Context, in *ListItemsByUserRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ChecklistService_ListItemsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecklistItem)
	err := c.cc.Invoke(ctx, ChecklistService_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) UpdateItemDates(ctx context.Context, in *UpdateItemDatesRequest, opts ...grpc.CallOption) (*ChecklistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecklistItem)
	err := c.cc.Invoke(ctx, ChecklistService_UpdateItemDates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) ArchiveItem(ctx context.Context, in *ArchiveItemRequest, opts ...grpc.CallOption) (*ChecklistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecklistItem)
	err := c.cc.Invoke(ctx, ChecklistService_ArchiveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChecklistService_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checklistServiceClient) DailyReset(ctx context.Context, in *DailyResetRequest, opts ...grpc.CallOption) (*DailyResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyResetResponse)
	err := c.cc.Invoke(ctx, ChecklistService_DailyReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChecklistServiceServer is the server API for ChecklistService service.
// All implementations must embed UnimplementedChecklistServiceServer
// for forward compatibility.
//
// ChecklistService — manages checklist items scoped to plans. Same package
// as PlanService because both belong to plan-service; one binary, two server
// registrations.
type ChecklistServiceServer interface {
	CreateItem(context.Context, *CreateItemRequest) (*ChecklistItem, error)
	GetItem(context.Context, *GetItemRequest) (*ChecklistItem, error)
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	ListArchivedItems(context.Context, *ListArchivedItemsRequest) (*ListItemsResponse, error)
	ListUpcomingItems(context.Context, *ListUpcomingItemsRequest) (*ListItemsResponse, error)
	ListItemsByUser(context.Context, *ListItemsByUserRequest) (*ListItemsResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*ChecklistItem, error)
	UpdateItemDates(context.Context, *UpdateItemDatesRequest) (*ChecklistItem, error)
	ArchiveItem(context.Context, *ArchiveItemRequest) (*ChecklistItem, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error)
	// DailyReset un-completes all daily-scope items across all plans (job-scheduled,
	// called from the gateway's nightly job in 4c).
	DailyReset(context.Context, *DailyResetRequest) (*DailyResetResponse, error)
	mustEmbedUnimplementedChecklistServiceServer()
}

// UnimplementedChecklistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChecklistServiceServer struct{}

func (UnimplementedChecklistServiceServer) CreateItem(context.Context, *CreateItemRequest) (*ChecklistItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedChecklistServiceServer) GetItem(context.Context, *GetItemRequest) (*ChecklistItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedChecklistServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedChecklistServiceServer) ListArchivedItems(context.Context, *ListArchivedItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArchivedItems not implemented")
}
func (UnimplementedChecklistServiceServer) ListUpcomingItems(context.Context, *ListUpcomingItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUpcomingItems not implemented")
}
func (UnimplementedChecklistServiceServer) ListItemsByUser(context.Context, *ListItemsByUserRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemsByUser not implemented")
}
func (UnimplementedChecklistServiceServer) UpdateItem(context.Context, *UpdateItemRequest) (*ChecklistItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedChecklistServiceServer) UpdateItemDates(context.Context, *UpdateItemDatesRequest) (*ChecklistItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItemDates not implemented")
}
func (UnimplementedChecklistServiceServer) ArchiveItem(context.Context, *ArchiveItemRequest) (*ChecklistItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveItem not implemented")
}
func (UnimplementedChecklistServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedChecklistServiceServer) DailyReset(context.Context, *DailyResetRequest) (*DailyResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyReset not implemented")
}
func (UnimplementedChecklistServiceServer) mustEmbedUnimplementedChecklistServiceServer() {}
func (UnimplementedChecklistServiceServer) testEmbeddedByValue()                          {}

// UnsafeChecklistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChecklistServiceServer will
// result in compilation errors.
type UnsafeChecklistServiceServer interface {
	mustEmbedUnimplementedChecklistServiceServer()
}

func RegisterChecklistServiceServer(s grpc.ServiceRegistrar, srv ChecklistServiceServer) {
	// If the following call pancis, it indicates UnimplementedChecklistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChecklistService_ServiceDesc, srv)
}

func _ChecklistService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_ListArchivedItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchivedItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).ListArchivedItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_ListArchivedItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).ListArchivedItems(ctx, req.(*ListArchivedItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_ListUpcomingItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpcomingItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).ListUpcomingItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_ListUpcomingItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).ListUpcomingItems(ctx, req.(*ListUpcomingItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_ListItemsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).ListItemsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_ListItemsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).ListItemsByUser(ctx, req.(*ListItemsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_UpdateItemDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).UpdateItemDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_UpdateItemDates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).UpdateItemDates(ctx, req.(*UpdateItemDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_ArchiveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).ArchiveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_ArchiveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).ArchiveItem(ctx, req.(*ArchiveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChecklistService_DailyReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DailyResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChecklistServiceServer).DailyReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChecklistService_DailyReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChecklistServiceServer).DailyReset(ctx, req.(*DailyResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChecklistService_ServiceDesc is the grpc.ServiceDesc for ChecklistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChecklistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plan.ChecklistService",
	HandlerType: (*ChecklistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _ChecklistService_CreateItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ChecklistService_GetItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _ChecklistService_ListItems_Handler,
		},
		{
			MethodName: "ListArchivedItems",
			Handler:    _ChecklistService_ListArchivedItems_Handler,
		},
		{
			MethodName: "ListUpcomingItems",
			Handler:    _ChecklistService_ListUpcomingItems_Handler,
		},
		{
			MethodName: "ListItemsByUser",
			Handler:    _ChecklistService_ListItemsByUser_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _ChecklistService_UpdateItem_Handler,
		},
		{
			MethodName: "UpdateItemDates",
			Handler:    _ChecklistService_UpdateItemDates_Handler,
		},
		{
			MethodName: "ArchiveItem",
			Handler:    _ChecklistService_ArchiveItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ChecklistService_DeleteItem_Handler,
		},
		{
			MethodName: "DailyReset",
			Handler:    _ChecklistService_DailyReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plan/checklist.proto",
}
