// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.1
// source: api/proto/events/insights.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailureClass is the vocabulary for WHY a plan's generation ended badly.
//
// It is an enum rather than a free string because it crosses a service boundary
// and the consumer switches on it to pick user-facing copy and to decide whether
// a retry action appears at all (FS-0006 R37). A free string lets the producer
// and the consumer disagree with nothing to catch it — the same silent drift the
// rest of this package exists to prevent.
//
// Values are added only for failures the system actually produces, never
// speculatively. Note the absence of a "poison"/"bug" class: that path
// dead-letters and publishes no event, so it never travels on this wire
// (FS-0006 R29). plan-service sets STALLED locally from its sweeper rather than
// receiving it, but the vocabulary is shared so the client sees one set of
// values whatever produced them.
type FailureClass int32

const (
	// Zero value, and deliberately not retryable — see Retryable(). A producer
	// that leaves it unset is a bug, and the consumer must fail toward the
	// conservative answer rather than offering a button that spends money.
	FailureClass_FAILURE_CLASS_UNSPECIFIED FailureClass = 0
	// Transient failures survived the full backoff ladder (FS-0006 R27).
	// Nothing is broken, so retrying on the spot is the fastest recovery.
	FailureClass_FAILURE_CLASS_GENERATION_EXHAUSTED FailureClass = 1
	// No outcome ever arrived and the sweeper gave up (FS-0006 R31). A panic or
	// OOM runs no error handler, so nothing reported; the work may simply be gone.
	FailureClass_FAILURE_CLASS_STALLED FailureClass = 2
)

// Enum value maps for FailureClass.
var (
	FailureClass_name = map[int32]string{
		0: "FAILURE_CLASS_UNSPECIFIED",
		1: "FAILURE_CLASS_GENERATION_EXHAUSTED",
		2: "FAILURE_CLASS_STALLED",
	}
	FailureClass_value = map[string]int32{
		"FAILURE_CLASS_UNSPECIFIED":          0,
		"FAILURE_CLASS_GENERATION_EXHAUSTED": 1,
		"FAILURE_CLASS_STALLED":              2,
	}
)

func (x FailureClass) Enum() *FailureClass {
	p := new(FailureClass)
	*p = x
	return p
}

func (x FailureClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureClass) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_events_insights_proto_enumTypes[0].Descriptor()
}

func (FailureClass) Type() protoreflect.EnumType {
	return &file_api_proto_events_insights_proto_enumTypes[0]
}

func (x FailureClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureClass.Descriptor instead.
func (FailureClass) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{0}
}

// InsightItem is one item out of a generated Insight — the CREATABLE SUBSET of a
// checklist item, deliberately the same shape as one, minus everything the
// database owns.
//
// Named for its ORIGIN, not its destination. It is never persisted in this
// shape: it exists for exactly one hop and is dead the instant the materializing
// transaction commits. Calling it a "generated item" would collide with
// plan-service's `generated` item STATUS (CONTEXT.md), which is the term
// ADR-0007 leans on when deciding what a regeneration is allowed to destroy —
// and that is the last word in this design that should be ambiguous. No id, plan_id, status,
// done, created_at or updated_at: those are assigned by the materializing
// transaction, not carried on the wire.
//
// There is intentionally NO sequence field. ARRAY ORDER IS SEQUENCE. An explicit
// field could disagree with the order it sits in; order cannot disagree with
// itself (FS-0006 R19c).
//
// There are intentionally NO dates. AI auto-scheduling of start_date / due_date
// is an unshipped plan-service capability; materialized items arrive unscheduled
// (FS-0006 R19d).
type InsightItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// "daily" | "longterm" — plan-service's checklist scope.
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// "task" | "note".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Index into the SAME items array identifying this item's parent, because no
	// row IDs exist before the materialization transaction opens (FS-0006 R19b).
	//
	// `optional` is load-bearing: without it, proto3 cannot distinguish "no parent"
	// from "parent is index 0", and index 0 is a legal parent.
	ParentIndex   *int32 `protobuf:"varint,4,opt,name=parent_index,json=parentIndex,proto3,oneof" json:"parent_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightItem) Reset() {
	*x = InsightItem{}
	mi := &file_api_proto_events_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightItem) ProtoMessage() {}

func (x *InsightItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightItem.ProtoReflect.Descriptor instead.
func (*InsightItem) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{0}
}

func (x *InsightItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InsightItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *InsightItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InsightItem) GetParentIndex() int32 {
	if x != nil && x.ParentIndex != nil {
		return *x.ParentIndex
	}
	return 0
}

// InsightGeneratedEvent carries the generated items themselves, so plan-service
// materializes without calling back and never depends on insights being
// reachable (FS-0006 R19).
type InsightGeneratedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*InsightItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightGeneratedEvent) Reset() {
	*x = InsightGeneratedEvent{}
	mi := &file_api_proto_events_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightGeneratedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightGeneratedEvent) ProtoMessage() {}

func (x *InsightGeneratedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightGeneratedEvent.ProtoReflect.Descriptor instead.
func (*InsightGeneratedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{1}
}

func (x *InsightGeneratedEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *InsightGeneratedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsightGeneratedEvent) GetItems() []*InsightItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// InsightGenerationFailedEvent is published when TRANSIENT retries are exhausted
// — not for poison messages, which dead-letter instead (FS-0006 R26, R27).
//
// failure_class travels with it because "failed" alone cannot drive the two
// things that depend on it: what the user is told, and whether a retry action is
// offered at all (FS-0006 R37).
type InsightGenerationFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FailureClass  FailureClass           `protobuf:"varint,3,opt,name=failure_class,json=failureClass,proto3,enum=events.FailureClass" json:"failure_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightGenerationFailedEvent) Reset() {
	*x = InsightGenerationFailedEvent{}
	mi := &file_api_proto_events_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightGenerationFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightGenerationFailedEvent) ProtoMessage() {}

func (x *InsightGenerationFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightGenerationFailedEvent.ProtoReflect.Descriptor instead.
func (*InsightGenerationFailedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{2}
}

func (x *InsightGenerationFailedEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *InsightGenerationFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsightGenerationFailedEvent) GetFailureClass() FailureClass {
	if x != nil {
		return x.FailureClass
	}
	return FailureClass_FAILURE_CLASS_UNSPECIFIED
}

var File_api_proto_events_insights_proto protoreflect.FileDescriptor

var file_api_proto_events_insights_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x69, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x49, 0x6e,
	0x73, 0x69, 0x67, 0x68, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0b, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a,
	0x0d, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x74,
	0x0a, 0x15, 0x49, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x49, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x1c, 0x49, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x2a, 0x70, 0x0a, 0x0c, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x5f, 0x43, 0x4c,
	0x41, 0x53, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x26, 0x0a, 0x22, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x5f, 0x43, 0x4c, 0x41,
	0x53, 0x53, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x58,
	0x48, 0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x41, 0x49,
	0x4c, 0x55, 0x52, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x72, 0x6b, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x4b, 0x4e, 0x2f,
	0x66, 0x69, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_events_insights_proto_rawDescOnce sync.Once
	file_api_proto_events_insights_proto_rawDescData = file_api_proto_events_insights_proto_rawDesc
)

func file_api_proto_events_insights_proto_rawDescGZIP() []byte {
	file_api_proto_events_insights_proto_rawDescOnce.Do(func() {
		file_api_proto_events_insights_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_events_insights_proto_rawDescData)
	})
	return file_api_proto_events_insights_proto_rawDescData
}

var file_api_proto_events_insights_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_events_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_events_insights_proto_goTypes = []any{
	(FailureClass)(0),                    // 0: events.FailureClass
	(*InsightItem)(nil),                  // 1: events.InsightItem
	(*InsightGeneratedEvent)(nil),        // 2: events.InsightGeneratedEvent
	(*InsightGenerationFailedEvent)(nil), // 3: events.InsightGenerationFailedEvent
}
var file_api_proto_events_insights_proto_depIdxs = []int32{
	1, // 0: events.InsightGeneratedEvent.items:type_name -> events.InsightItem
	0, // 1: events.InsightGenerationFailedEvent.failure_class:type_name -> events.FailureClass
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_events_insights_proto_init() }
func file_api_proto_events_insights_proto_init() {
	if File_api_proto_events_insights_proto != nil {
		return
	}
	file_api_proto_events_insights_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_events_insights_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_insights_proto_goTypes,
		DependencyIndexes: file_api_proto_events_insights_proto_depIdxs,
		EnumInfos:         file_api_proto_events_insights_proto_enumTypes,
		MessageInfos:      file_api_proto_events_insights_proto_msgTypes,
	}.Build()
	File_api_proto_events_insights_proto = out.File
	file_api_proto_events_insights_proto_rawDesc = nil
	file_api_proto_events_insights_proto_goTypes = nil
	file_api_proto_events_insights_proto_depIdxs = nil
}
