// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.1
// source: api/proto/events/insights.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeneratedItem is the CREATABLE SUBSET of a checklist item — deliberately the
// same shape as one, minus everything the database owns. No id, plan_id, status,
// done, created_at or updated_at: those are assigned by the materializing
// transaction, not carried on the wire.
//
// There is intentionally NO sequence field. ARRAY ORDER IS SEQUENCE. An explicit
// field could disagree with the order it sits in; order cannot disagree with
// itself (FS-0006 R19c).
//
// There are intentionally NO dates. AI auto-scheduling of start_date / due_date
// is an unshipped plan-service capability; materialized items arrive unscheduled
// (FS-0006 R19d).
type GeneratedItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// "daily" | "longterm" — plan-service's checklist scope.
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// "task" | "note".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Index into the SAME items array identifying this item's parent, because no
	// row IDs exist before the materialization transaction opens (FS-0006 R19b).
	//
	// `optional` is load-bearing: without it, proto3 cannot distinguish "no parent"
	// from "parent is index 0", and index 0 is a legal parent.
	ParentIndex   *int32 `protobuf:"varint,4,opt,name=parent_index,json=parentIndex,proto3,oneof" json:"parent_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedItem) Reset() {
	*x = GeneratedItem{}
	mi := &file_api_proto_events_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedItem) ProtoMessage() {}

func (x *GeneratedItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedItem.ProtoReflect.Descriptor instead.
func (*GeneratedItem) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratedItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GeneratedItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GeneratedItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneratedItem) GetParentIndex() int32 {
	if x != nil && x.ParentIndex != nil {
		return *x.ParentIndex
	}
	return 0
}

// InsightGeneratedEvent carries the generated items themselves, so plan-service
// materializes without calling back and never depends on insights being
// reachable (FS-0006 R19).
type InsightGeneratedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*GeneratedItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightGeneratedEvent) Reset() {
	*x = InsightGeneratedEvent{}
	mi := &file_api_proto_events_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightGeneratedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightGeneratedEvent) ProtoMessage() {}

func (x *InsightGeneratedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightGeneratedEvent.ProtoReflect.Descriptor instead.
func (*InsightGeneratedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{1}
}

func (x *InsightGeneratedEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *InsightGeneratedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsightGeneratedEvent) GetItems() []*GeneratedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// InsightGenerationFailedEvent is published when TRANSIENT retries are exhausted
// — not for poison messages, which dead-letter instead (FS-0006 R26, R27).
//
// failure_class travels with it because "failed" alone cannot drive the two
// things that depend on it: what the user is told, and whether a retry action is
// offered at all (FS-0006 R37).
type InsightGenerationFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FailureClass  string                 `protobuf:"bytes,3,opt,name=failure_class,json=failureClass,proto3" json:"failure_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightGenerationFailedEvent) Reset() {
	*x = InsightGenerationFailedEvent{}
	mi := &file_api_proto_events_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightGenerationFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightGenerationFailedEvent) ProtoMessage() {}

func (x *InsightGenerationFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightGenerationFailedEvent.ProtoReflect.Descriptor instead.
func (*InsightGenerationFailedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_insights_proto_rawDescGZIP(), []int{2}
}

func (x *InsightGenerationFailedEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *InsightGenerationFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsightGenerationFailedEvent) GetFailureClass() string {
	if x != nil {
		return x.FailureClass
	}
	return ""
}

var File_api_proto_events_insights_proto protoreflect.FileDescriptor

var file_api_proto_events_insights_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x69, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x0d, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x42,
	0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x76, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x69, 0x67, 0x68, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x75, 0x0a, 0x1c, 0x49, 0x6e, 0x73, 0x69,
	0x67, 0x68, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61,
	0x72, 0x6b, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x4b, 0x4e, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_events_insights_proto_rawDescOnce sync.Once
	file_api_proto_events_insights_proto_rawDescData = file_api_proto_events_insights_proto_rawDesc
)

func file_api_proto_events_insights_proto_rawDescGZIP() []byte {
	file_api_proto_events_insights_proto_rawDescOnce.Do(func() {
		file_api_proto_events_insights_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_events_insights_proto_rawDescData)
	})
	return file_api_proto_events_insights_proto_rawDescData
}

var file_api_proto_events_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_events_insights_proto_goTypes = []any{
	(*GeneratedItem)(nil),                // 0: events.GeneratedItem
	(*InsightGeneratedEvent)(nil),        // 1: events.InsightGeneratedEvent
	(*InsightGenerationFailedEvent)(nil), // 2: events.InsightGenerationFailedEvent
}
var file_api_proto_events_insights_proto_depIdxs = []int32{
	0, // 0: events.InsightGeneratedEvent.items:type_name -> events.GeneratedItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_events_insights_proto_init() }
func file_api_proto_events_insights_proto_init() {
	if File_api_proto_events_insights_proto != nil {
		return
	}
	file_api_proto_events_insights_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_events_insights_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_insights_proto_goTypes,
		DependencyIndexes: file_api_proto_events_insights_proto_depIdxs,
		MessageInfos:      file_api_proto_events_insights_proto_msgTypes,
	}.Build()
	File_api_proto_events_insights_proto = out.File
	file_api_proto_events_insights_proto_rawDesc = nil
	file_api_proto_events_insights_proto_goTypes = nil
	file_api_proto_events_insights_proto_depIdxs = nil
}
