// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/insights/insights.proto

package insights

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsightsService_GenerateSuggestion_FullMethodName       = "/insights.InsightsService/GenerateSuggestion"
	InsightsService_GenerateDailySuggestions_FullMethodName = "/insights.InsightsService/GenerateDailySuggestions"
	InsightsService_SuggestVideos_FullMethodName            = "/insights.InsightsService/SuggestVideos"
)

// InsightsServiceClient is the client API for InsightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InsightsService — AI-generated productivity suggestions for a plan. It owns no
// durable data of its own today; it reads plan focus + checklist items from
// plan-service over gRPC and calls an LLM to produce suggestions. The reserved
// insights-service-db (ordinal 6) is for future caching/persistence of
// generated insights.
//
// user_id is carried on every request so insights can assert plan ownership
// against plan-service before generating anything (same trust model as the
// other services: the gateway authenticates and forwards the user_id).
type InsightsServiceClient interface {
	// GenerateSuggestion returns a single, actionable next checklist item for the
	// plan, derived from its focus + current checklist.
	GenerateSuggestion(ctx context.Context, in *GenerateSuggestionRequest, opts ...grpc.CallOption) (*GenerateSuggestionResponse, error)
	// GenerateDailySuggestions returns a handful of daily focus suggestions
	// derived from longterm checklist items + plan focus.
	GenerateDailySuggestions(ctx context.Context, in *GenerateDailySuggestionsRequest, opts ...grpc.CallOption) (*GenerateDailySuggestionsResponse, error)
	// SuggestVideos returns recommended learning videos for the plan.
	SuggestVideos(ctx context.Context, in *SuggestVideosRequest, opts ...grpc.CallOption) (*SuggestVideosResponse, error)
}

type insightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightsServiceClient(cc grpc.ClientConnInterface) InsightsServiceClient {
	return &insightsServiceClient{cc}
}

func (c *insightsServiceClient) GenerateSuggestion(ctx context.Context, in *GenerateSuggestionRequest, opts ...grpc.CallOption) (*GenerateSuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSuggestionResponse)
	err := c.cc.Invoke(ctx, InsightsService_GenerateSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GenerateDailySuggestions(ctx context.Context, in *GenerateDailySuggestionsRequest, opts ...grpc.CallOption) (*GenerateDailySuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDailySuggestionsResponse)
	err := c.cc.Invoke(ctx, InsightsService_GenerateDailySuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) SuggestVideos(ctx context.Context, in *SuggestVideosRequest, opts ...grpc.CallOption) (*SuggestVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestVideosResponse)
	err := c.cc.Invoke(ctx, InsightsService_SuggestVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsightsServiceServer is the server API for InsightsService service.
// All implementations must embed UnimplementedInsightsServiceServer
// for forward compatibility.
//
// InsightsService — AI-generated productivity suggestions for a plan. It owns no
// durable data of its own today; it reads plan focus + checklist items from
// plan-service over gRPC and calls an LLM to produce suggestions. The reserved
// insights-service-db (ordinal 6) is for future caching/persistence of
// generated insights.
//
// user_id is carried on every request so insights can assert plan ownership
// against plan-service before generating anything (same trust model as the
// other services: the gateway authenticates and forwards the user_id).
type InsightsServiceServer interface {
	// GenerateSuggestion returns a single, actionable next checklist item for the
	// plan, derived from its focus + current checklist.
	GenerateSuggestion(context.Context, *GenerateSuggestionRequest) (*GenerateSuggestionResponse, error)
	// GenerateDailySuggestions returns a handful of daily focus suggestions
	// derived from longterm checklist items + plan focus.
	GenerateDailySuggestions(context.Context, *GenerateDailySuggestionsRequest) (*GenerateDailySuggestionsResponse, error)
	// SuggestVideos returns recommended learning videos for the plan.
	SuggestVideos(context.Context, *SuggestVideosRequest) (*SuggestVideosResponse, error)
	mustEmbedUnimplementedInsightsServiceServer()
}

// UnimplementedInsightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsightsServiceServer struct{}

func (UnimplementedInsightsServiceServer) GenerateSuggestion(context.Context, *GenerateSuggestionRequest) (*GenerateSuggestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSuggestion not implemented")
}
func (UnimplementedInsightsServiceServer) GenerateDailySuggestions(context.Context, *GenerateDailySuggestionsRequest) (*GenerateDailySuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDailySuggestions not implemented")
}
func (UnimplementedInsightsServiceServer) SuggestVideos(context.Context, *SuggestVideosRequest) (*SuggestVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestVideos not implemented")
}
func (UnimplementedInsightsServiceServer) mustEmbedUnimplementedInsightsServiceServer() {}
func (UnimplementedInsightsServiceServer) testEmbeddedByValue()                         {}

// UnsafeInsightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightsServiceServer will
// result in compilation errors.
type UnsafeInsightsServiceServer interface {
	mustEmbedUnimplementedInsightsServiceServer()
}

func RegisterInsightsServiceServer(s grpc.ServiceRegistrar, srv InsightsServiceServer) {
	// If the following call pancis, it indicates UnimplementedInsightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsightsService_ServiceDesc, srv)
}

func _InsightsService_GenerateSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GenerateSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GenerateSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GenerateSuggestion(ctx, req.(*GenerateSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GenerateDailySuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDailySuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GenerateDailySuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GenerateDailySuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GenerateDailySuggestions(ctx, req.(*GenerateDailySuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_SuggestVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).SuggestVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_SuggestVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).SuggestVideos(ctx, req.(*SuggestVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsightsService_ServiceDesc is the grpc.ServiceDesc for InsightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insights.InsightsService",
	HandlerType: (*InsightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateSuggestion",
			Handler:    _InsightsService_GenerateSuggestion_Handler,
		},
		{
			MethodName: "GenerateDailySuggestions",
			Handler:    _InsightsService_GenerateDailySuggestions_Handler,
		},
		{
			MethodName: "SuggestVideos",
			Handler:    _InsightsService_SuggestVideos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/insights/insights.proto",
}
